version: '2'
services:
    tests:
        build:
            context: .
        network_mode: "host"
        cap_add:
            - SYS_PTRACE

    clickhouse:
        image: yandex/clickhouse-server
        ports:
            - "8123:8123"
            - "9000:9000"
        network_mode: "host"

    client:
        image: yandex/clickhouse-client
        network_mode: "host"
